name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        pythonVersion: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Anaconda-Action
      id: step1
      uses: fdiblen/anaconda-action@0.1.7
      with:
        envFileName: 'environment.yml'
    - name: Install dependencies
      run: |
        conda create -y -n TEST python=3.7 --file environment.txt
        source activate TEST
        conda info --envs
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        printenv
        pytest 
