name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Run setup-conda
        uses: s-weigand/setup-conda@v1
        with:
          activate-conda: true
      - name: Install dependencies
        run: |
          conda create -y -n TEST python=3.7 --file environment.txt
          source activate TEST
          conda info --envs
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          printenv
      - name: Run tests with pytest
        run: |
          pip install pytest
          pytest 
