name: Test Conda Env

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: s-weigand/setup-conda@v1
        with:
          activate-conda: false
      - name: Check Python version
        run: |
           conda --version
           which python
           python --version
           python -c "import sys;print(sys.executable);print(sys.version_info)"
      - name: Check env
        run: printenv
      - name: Install and check pandoc version
        run: |
           conda install pandoc
           pandoc -v
